### ISSUE TITLE
Is this library supported on Android and iOS?

### ISSUE THREAD

**Issue by candybongduk** [VernierST/godirect-examples#33]
Hi

Thanks for sharing this module and I was wondering if this godirect and gdx module are also supported on Android and iOS?

Thanks

**Comment by dvernier** [comment]
Vernier has a free app called Graphical Analysis for both iOS and Android. 

We also have Python and JavaScript program example on our web site www.vernier.com.

**Comment by sswartley** [comment]
@candybongduk  The JavaScript library should work with Android. This library uses a Bluetooth Low Energy (BLE) connection via Web Bluetooth. Currently iOS devices are not compatible with this protocol, but Android is capable of using this.

**Comment by candybongduk** [comment]
Thanks for your prompt and kind answers. That was a great help for me as I was trying to make my own app using this go-direct module.
