### ISSUE TITLE
Error: Linux (Ubuntu 16.04), Python(3), BlueZ(5.46): Open Error (While connecting to the device)

### ISSUE THREAD

**Issue by WangJihan** [VernierST/godirect-examples#34]
Hi, while we are using gdx_getting_started_bluetooth.py, we occur an error from the line: 
`gdx.open_usb()`
this line will lead to the line from gdx.py line 153:
`open_device_success = gdx.devices[i].open()`
And while running this line, the error as follow occurs:
`  File "hid.pyx", line 74, in hid.device.open_path
OSError: open failed`
Could anyone please help me with this problem? While we are using another Linux pc, we still get this error, and while turning to windows, the error disappears, so this might be due to the Linux system, I suppose.

**Comment by stocktonkincade** [comment]
Firstly, make sure you have followed the [install steps for Linux](https://github.com/VernierST/godirect-examples/tree/master/python#linux-and-linux-on-raspberry-pi). Also, that example should not be calling into gdx.open_usb(), at all. Are you sure you were not running the gdx_getting_started_usb.py example?

**Comment by WangJihan** [comment]
Hi, thank you for your reply. yes, I have followed the installation guidence.  
I have a typo on the gdx.open_usb(), it should be gdx.open_ble().
I am trying the gdx_getting_started_bluetooth.py example, but I still get an error when opening. The device can be found but cannot be opened. Here is a screenshot for the error occurred. 

![image](https://user-images.githubusercontent.com/68939895/109900861-fe846d00-7cd2-11eb-9859-20ffec2339b6.png)

**Comment by stocktonkincade** [comment]
I was able to reproduce the problem on a Linux box with godirect v1.0.7 and bleak v0.5.0. I updated bleak by running:

> pip3 install bleak

That put me at bleak v0.10.0. At this point, I was able to run the example, to completion. Please let me know if that helps. If not, please let me know which versions of godirect and bleak you have installed

> pip3 list|grep 'bleak\|godirect'
