### ISSUE TITLE
Error referring to missing "gdxcc module"

### ISSUE THREAD

**Issue by webere13** [VernierST/godirect-examples#35]
So I have followed the installation guide step by step and keep running into this error (below) when attempting to run my own code + any of the pre-made codes offered here. I have gotten the code to work on another raspberryPi and have not seen this "gdxcc" module mentioned in my search of the error. I'm using python 3.7.3 and raspberryPi model 3 B+
![IMG_8368](https://user-images.githubusercontent.com/83022174/115737538-3b2b2700-a35a-11eb-98ed-62a973b3066b.jpg)

**Comment by stocktonkincade** [comment]
Make sure that the gdx folder is in the right location. That folder contains the gdx helper object, it is not a pip installed module, so it needs to be in the same folder as your Collect.py script. Also, you probably have another python module (gdxcc) installed that has the gdx name. You can also see all of your installed modules with: `pip3 list`. I think that, as long as the gdx folder is in the right place, it will resolve it, but you may need uninstall the `gdxcc` module.
