### ISSUE TITLE
Missing readings from Go Direct Respiration Belt

### ISSUE THREAD

**Issue by gfwilliams** [VernierST/godirect-examples#37]
Hi!

I've been trying to use the Go Direct JS library (as well as communicating directly via Bluetooth LE from a Bangle.js smart watch), and while I seem to be able to get readings ok, there seems to be a pause in data gathering pretty much once a second, during which data appears to be lost. I see the same effect on both platforms so I don't believe this is OS or bluetooth related.

To try and illustrate the example, I used the example code from https://vernierst.github.io/godirect-examples/javascript//gdx_getting_started_2.html and instead of reporting the sensor values, I just output the time between readings (code at https://gist.github.com/gfwilliams/74fad51b49e9c7f6798c63f575ed055a). The following is reported

```
106 ms
 96 ms
 98 ms
 104 ms
 98 ms
 97 ms
 518 ms <---------
 578 ms <---------
 104 ms
 97 ms
 98 ms
 106 ms
 96 ms
 99 ms
 106 ms
 96 ms
 97 ms
 503 ms <---------
 601 ms <---------
 96 ms
 99 ms
 96 ms
 106 ms
 96 ms
 98 ms
 106 ms
 97 ms
 98 ms
 458 ms <---------
 644 ms <---------
 99 ms
 96 ms
 105 ms
 97 ms
 98 ms
 97 ms
 106 ms
 96 ms
 99 ms
 442 ms <---------
 660 ms <---------
 98 ms
 96 ms
 107 ms
 96 ms
 120 ms
```

So it seems like I should be getting 10 Hz data readings, which seems sensible, however there are big pauses, pretty reliably, roughly every second. If I graph the data and breathe quickly enough, it's pretty obvious that readings are being lost during the pauses, rather than it being a ~5Hz signal that's transmitted sometimes quick, sometimes slow

Any ideas what could be the problem? Thanks!

**Comment by stocktonkincade** [comment]
I do not have a GDX-RB on hand at the moment, but I have a few thoughts.
- To eliminate any chance that the device is misbehaving, have you tried to use it with the free Vernier Graphical Analysis software and replicate the same sampling period?
- This device enables both the Force and Respiration Rate channels by default. The later is periodically computed from accumulated Force measurements. You example code will be intermingling the two channels into the output of your 'value-changed' handler. See what you get when you show the results by channel. Here is a trivial modification to your example:

```
sensor.on('value-changed', (sensor) => {
  var now = Date.now();
  var t = Math.round(now-lastInfo);
  console.log(`${t} ms (${sensor.number})`);
  if (t > 1) {
  output.textContent += `\n ${t} ms`;
  lastInfo = now;
}
```

**Comment by gfwilliams** [comment]
>  have you tried to use it with the free Vernier Graphical Analysis software and replicate the same sampling period?

Actually I just did that (should have done this before) and I see the exact same thing. So it's a hardware issue...

Any idea what I can do? Are there software updates available for the devices? Where could I report an issue?

**Comment by gfwilliams** [comment]
Ok, just checked - it's on firmware 4.11.0 / 4.1.0, which appears to be up to date (I don't get any firmware prompt). Manufactured May '21 so should be pretty new anyway.

I'm pretty sure I found the issue...

I've tried:  Chromebook Graphical Analysis, Android Graphical Analysis, godirect.js on Android/Linux/Chromebook

Basically: 

* If you power on the sensor and connect via Bluetooth, you see the pause in readings I mentioned
* If you power on the sensor and connect via USB, it works fine
* If you power on the sensor and connect the Graphical Analysis app via USB, **then disconnect and reconnect via bluetooth without powering off the sensor** then it also works fine!

So either some extra config is being done when connected via USB, or it looks like a firmware bug :(

**Comment by stocktonkincade** [comment]
Thank you for the details. We have seen a similar behavior on a few other pieces of hardware. We have not determined the exact cause, but believe it is a hardware timing issue that could possibly be fixed in firmware. The workaround you found (connect via USB first) is the only thing that can be done in the field at the moment. Unless, of course, you are able to exchange that unit for another one.

**Comment by gfwilliams** [comment]
Ok, thanks... That's a shame - it does make it a complete pain to use.

> Unless, of course, you are able to exchange that unit for another one.

Do some units work ok and some don't then?

**Comment by stocktonkincade** [comment]
Yes, it has been our experience that only this behavior is only on the rare unit. We are currently looking into the problem and hope to find a firmware solution that we can distribute to the field. We will try to reach out to you if/when we find a solution.

**Comment by gfwilliams** [comment]
Ok, great. Do you think it would be sensible to contact my distributor and ask for a replacement unit then?

**Comment by stocktonkincade** [comment]
I will contact you directly via your listed contact email.

**Comment by stocktonkincade** [comment]
We have found a firmware fix for this problem. It has not yet been distributed through our Graphical Analysis application, but we may be able to provide it on request.

**Comment by gfwilliams** [comment]
Ok, that's great. I could really do with the firmware update for this as it makes the belt a bit hard to use reliably right now

**Comment by stocktonkincade** [comment]
@gfwilliams can we start a direct email thread for this, please? I can send an opening message to the address listed in your github profile. If that will not work, please let me know.
