### ISSUE TITLE
GoDirect Connection Fails - Event loop already running 

### ISSUE THREAD

**Issue by gorbx** [VernierST/godirect-examples#38]
Hello, I am trying to connect to a godirect respiration sensor via bluetooth, and am getting the same error on two different PC's, so I'm wondering if I'm missing something very simple. 

The code that I'm trying to run is below, and the error I get is below that.

Things I have tried:
- changing open_ble() to target the specific device
- adding import nest_asyncio and nest_asyncio.apply() to backend_bleak.py, which just causes a different error

Any advice greatly appreciated.

` 
import gdx
gdx = gdx.gdx()
  
gdx.open_ble()

gdx.select_sensors([1])
gdx.start() 

for i in range(0,20):
    measurements = gdx.read()
    if measurements == None:
        break 
    print(measurements)

gdx.stop()
gdx.close()`

`wait for bluetooth initialization...
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
c:\Dropbox (MIT)\RESEARCH\TESTINGPOD\POD_GITHUB\POD_vernier.py in <module>
     19 
     20 # gdx.open_ble("GDX-RB 0K3010Q3")
---> 21 gdx.open_ble()
     22 
     23 gdx.select_sensors([1])

c:\Dropbox (MIT)\RESEARCH\TESTINGPOD\POD_GITHUB\gdx.py in open_ble(self, device_to_open)
     85 
     86         # Find all available bluetooth devices
---> 87         found_devices = self.godirect.list_devices()
     88         number_found_devices = len(found_devices)
     89         print("number of ble devices found = " +str(number_found_devices))

C:\Python\Python39\lib\site-packages\godirect\__init__.py in list_devices(self)
     71                         self._devices += self._usb_backend.scan()
     72                 if self._ble_backend != None:
---> 73                         self._devices += self._ble_backend.scan()
     74                 return self._devices
     75 

C:\Python\Python39\lib\site-packages\godirect\backend_bleak.py in scan(self)
     40 		"""
     41                 loop = asyncio.get_event_loop()
---> 42                 devices = loop.run_until_complete(self._async_scan())
     43 
     44                 return devices

C:\Python\Python39\lib\asyncio\base_events.py in run_until_complete(self, future)
    616         """
    617         self._check_closed()
--> 618         self._check_running()
    619 
    620         new_task = not futures.isfuture(future)

C:\Python\Python39\lib\asyncio\base_events.py in _check_running(self)
    576     def _check_running(self):
    577         if self.is_running():
--> 578             raise RuntimeError('This event loop is already running')
    579         if events._get_running_loop() is not None:
    580             raise RuntimeError(

RuntimeError: This event loop is already running`

**Comment by stocktonkincade** [comment]
I have not been able to reproduce this failure with either Python v3.7.4 or v3.10.0. I am running Win10, and have tried your code on both an Intel and Arm processor. That suggests there is something about your environment that may be changing the behavior. Here are some more things to look at.

* Make sure that you have all of the latest packages installed. Particularly godirect and bleak. Here is a `pip list` of the relevant packages my environment:
`bleak              0.13.0`
`bleak-winrt     1.0.1`
`godirect          1.1.2`
`hidapi              0.11.0.post2`

You can update to the latest with: `>pip install [packagename] --upgrade`

* Try running the bleak-lescan.exe that gets installed with bleak. Just open a command promt or Powershell window and run `>bleak-lescan'. It should take a few seconds and generate a list of nearby Bluetooth devices. This will at least tell us if the bleak package that we use for godirect is working on your system.
* Are you installing/running python in a virtual environment? I have successfully run your code in a venv, but it is not something we test very often.

**Comment by gorbx** [comment]
Hi - thank you for the quick responses! After checking everything, it turns out I was running the script incorrectly, using VSCODE's interactive mode. When running the script directly, it connects to the sensor and retrieves the data as intended.
