### ISSUE TITLE
Cannot sample any faster than 10 Hz when using Python

### ISSUE THREAD

**Issue by stocktonkincade** [VernierST/godirect-examples#4]
No matter which X I chose in "gdx.start(period=X)", I can't get output more quicker than 10 Hz. I have tested my EKG sensor in your software "Vernier Graphical Analysis" where it is possible to read and store measurements with a sample frequency of 200 Hz. When I write "gdx.start(period=5)" it still gives me the 10 Hz sampling frequency. Do you know why?

**Comment by stocktonkincade** [comment]
While many of the Go Direct devices can internally sample at rates faster than 10 Hz (samples/second), the Python layers create some bottle necks. Currently, sample intervals greater than ~50 ms (20 Hz) will work over USB and BLE. However, calling device.start() with a value less than ~51 ms, will result in sample intervals closer to 100 ms. This is likely due to the godirect module having to do 2 reads to the underlying pipe (BLE or USB) before aggregating a full measurement packet and returning to the user. We hope to find ways to increase the performance in the future.

It is also important to know that the Python code must perform a device.read() at least as fast as the requested sampling interval, as to not loose any measurements.

**Comment by jordanaustin** [comment]
@stocktonkincade seems like we should file a bug on https://github.com/VernierST/godirect-py/issues to track a fix at the source level

**Comment by stocktonkincade** [comment]
New bug created at: https://github.com/VernierST/godirect-py/issues/1
