### ISSUE TITLE
"IndexError: list assignment index out of range" error when running gdx.read() function

### ISSUE THREAD

**Issue by smdbqueens** [VernierST/godirect-examples#56]
I am trying to use the Vernier GoDirect Radiation Monitor for an experiment, but I am having issues running the gdx.read() function. When I used the code from the Getting Started website, I get the error "IndexError: list assignment index out of range."

The code I am using is as follows:

`from gdx import gdx`

`gdx=gdx.gdx()`

`gdx.open(connection='usb')`
`gdx.select_sensors()`
`gdx.start(1000)`

`for i in range(0,10):`
`    measurements = gdx.read()`
`    if measurements == None: `
`        break `
`    print(measurements)`

`gdx.stop()`
`gdx.close()`

And the error I am getting is as follows:

Traceback (most recent call last):
  File "c:\Users\smdb\Downloads\monitor.py", line 20, in <module>
    measurements = gdx.read()
  File "C:\Users\smdb\anaconda3\lib\site-packages\gdx\gdx.py", line 572, in read
    if gdx.devices[i].read():
  File "C:\Users\smdb\anaconda3\lib\site-packages\godirect\device.py", line 181, in read
    return self._GDX_read_measurement(timeout)
  File "C:\Users\smdb\anaconda3\lib\site-packages\godirect\device.py", line 401, in _GDX_read_measurement
    return self._GDX_handle_measurement(response)
  File "C:\Users\smdb\anaconda3\lib\site-packages\godirect\device.py", line 436, in _GDX_handle_measurement
    sensors[0] = self._sensors[sensor_number]
IndexError: list assignment index out of range

I've tried changing the values in the range as well as looking directly in the gdx.py file for any issue, but I am unable to do so. I would appreciate any help or advice you could offer to help me fix this issue.

**Comment by sswartley** [comment]
Hello,

I think there may be two issues that you are going to run in to. The first is that it looks like you are running Python in Anaconda? My understanding is that this does not work without some minor changes to the code. For now, I would suggest you do the initial troubleshooting just by running Python, without Anaconda.

The second issue that I think will arise is that there is a bug in the godirect library for timing events, such as trying to get data from a photogate for photogate timing. I have not tested to see if this same bug affects radiation counts, but I am assuming it might.

If it is possible, as a first step could you run the code without using Anaconda and see what the results of that change are?

All the best,

Sam

**Comment by smdbqueens** [comment]
Hello, thank your for your advice, however it didn't resolve our issue! We tried running the code without using Anaconda, just Python straight from the Windows Terminal, but encountered the same error IndexError as before. 

The code used is shown below. We tried several different ones including gdx_getting_started_usb.py from godirect-examples github. But the same error occurs. The code was run both with Python 3.11 and 3.7 from the Windows 11 terminal.

```
from gdx import gdx

gdx = gdx.gdx()

gdx.open(connection='usb')
gdx.select_sensors()
gdx.start(1000)

measurements = []
i = 0
while i < 10:
    measurements.append(gdx.read())
    i += 1

print(measurements)

gdx.stop()
gdx.close()
```

The error
````
C:\Users\smdb\AppData\Local\Programs\Python\Python37\python.exe .\Sensor_Collect.py


List of sensors for GDX-RAD 0C100719 USB
5: Radiation (Counts)


- If connecting a single sensor, type the number (e.g., 1) that
corresponds with the sensor, and then press 'enter'.
- If connecting multiple sensors, type in each number
separated with commas with no spaces(e.g., 1,2), and then
click 'enter': 5
Traceback (most recent call last):
  File ".\Sensor_Collect.py", line 12, in <module>
    measurements.append(gdx.read())
  File "C:\Users\smdb\AppData\Local\Programs\Python\Python37\lib\site-packages\gdx\gdx.py", line 572, in read
    if gdx.devices[i].read():
  File "C:\Users\smdb\AppData\Local\Programs\Python\Python37\lib\site-packages\godirect\device.py", line 181, in read
    return self._GDX_read_measurement(timeout)
  File "C:\Users\smdb\AppData\Local\Programs\Python\Python37\lib\site-packages\godirect\device.py", line 401, in _GDX_read_measurement
    return self._GDX_handle_measurement(response)
  File "C:\Users\smdb\AppData\Local\Programs\Python\Python37\lib\site-packages\godirect\device.py", line 436, in _GDX_handle_measurement
    sensors[0] = self._sensors[sensor_number]
IndexError: list assignment index out of range
````

Any further advice would be very helpful.

**Comment by stocktonkincade** [comment]
This may be a bug in our [godirect-py](https://github.com/VernierST/godirect-py/blob/main/godirect/device.py) code for this particular device. The radiation sensor is unique among our Go Direct devices, in that it is the only device that returns integer values (counts) over a given period. As such this is a code path in godirect-py that may have been overlooked or under tested. We will try and take a closer look, ASAP.

**Comment by sswartley** [comment]
Hello @smdbqueens ,

We have updated the godirect package to provide better support for the Go Direct sensors that perform counting operations, such as the Go Direct Radiation monitor. You can do a `pip install godirect --upgrade` to update to this newer version of godirect. Check to make sure that you are now running version 1.1.4 with a `pip show godirect`

I hope that gets you started.

All the best,

Sam
