### ISSUE TITLE
Go Direct sensor Bluetooth manual connections - CCCD information?

### ISSUE THREAD

**Issue by MGHOASIIS** [VernierST/godirect-examples#60]
Hello,

I was directed to ask a question here from the Vernier support team regarding difficulties manually connecting to a Go Direct Respiration Belt using Bluetooth.

I am attempting to connect to this sensor to a Unity game engine project using C#. While the connection to the sensor goes through smoothly, I am unable to receive a signal based on what I assume to be a CCCD that requires a nonstandard input. Here is the GATT table that I've discovered from the sensor:

Type | UUID | Permissions  | Purpose 
-- | -- | -- | --
**_Service_** | 00001800-0000-1000-8000-00805f9b34fb |   |  
Characteristic | 00002a00-0000-1000-8000-00805f9b34fb | Read | Device Name
Characteristic | 00002a01-0000-1000-8000-00805f9b34fb | Read | Appearance
**_Service_** | 0000180a-0000-1000-8000-00805f9b34fb |   |  
Characteristic | 00002a29-0000-1000-8000-00805f9b34fb | Read | Manufacturer Name
Characteristic | 00002a25-0000-1000-8000-00805f9b34fb | Read | Serial Number
Characteristic | 00002a26-0000-1000-8000-00805f9b34fb | Read | Firmware Revision
Characteristic | 00002a28-0000-1000-8000-00805f9b34fb | Read | Software Revision
**_Service_** | 0000180f-0000-1000-8000-00805f9b34fb |   |  
Characteristic | 00002a19-0000-1000-8000-00805f9b34fb | Read | Battery Level
**_Service_** | d91714ef-28b9-4f91-ba16-f0d9a604f112 |   |  
Characteristic | f4bf14a6-c7d5-4b6d-8aa8-df1a7c83adcb | Write (No Response) | ???
Characteristic | b41e6675-a329-40e0-aa01-44d2f444babe | Notify | CCCD Descriptor
**_Service_** | 8e6f0f58-5819-11e6-8b77-86f30ca893d3 |   |  
Characteristic | 8e6f094a-5819-11e6-8b77-86f30ca893d3 | Read | ???
Characteristic | 9cea5308-59a9-11e6-8b77-86f30ca893d3 | Write | ???
Characteristic | cf052904-5d95-11e6-8b77-86f30ca893d3 | Write | ???
Characteristic | 248d6f39-5819-11e6-8b77-86f30ca893d3 | Read/Write | ???

Attempting to write the standard 0x01 to enable notifications to the CCCD didn't seem to work, and I also tried it for all other writeable characteristics just to be sure. 

Is there more information on the GATT table for this sensor available anywhere, or any guidance on how to manually connect and start reading a signal? Any help is appreciated.

Thanks,
Caleb

**Comment by stocktonkincade** [comment]
The two characteristics under the d91714ef-28b9-4f91-ba16-f0d9a604f112 service are custom characteristics for the Go Direct devices. Basically a read/write pipe for proprietary commands. While we don't directly publish complete details, the protocol and some basic commands are described in code in both the [godirect-py](https://github.com/VernierST/godirect-py) and [godirect-js](https://github.com/VernierST/godirect-js) modules. If you are not using either of those modules directly, we cannot offer much support beyond what the open source projects reveal in code.
